package com.inventory.product.controller;
import java.math.BigDecimal;
import org.springframework.data.domain.Page;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import com.inventory.product.dto.ProductDto;
import com.inventory.product.service.ProductService;
import jakarta.validation.Valid;
@RestController @RequestMapping("/api/products") public class ProductController { private final ProductService productService; public ProductController(ProductService productService){this.productService=productService;} @PostMapping public ResponseEntity<ProductDto> save(@Valid @RequestBody ProductDto dto){return new ResponseEntity<>(productService.saveProduct(dto),HttpStatus.CREATED);} @GetMapping public ResponseEntity<Page<ProductDto>> all(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,@RequestParam(defaultValue="id")String sortBy,@RequestParam(defaultValue="asc")String sortDir){return ResponseEntity.ok(productService.getAllProducts(page,size,sortBy,sortDir));} @GetMapping("/{id}") public ResponseEntity<ProductDto> byId(@PathVariable Long id){return ResponseEntity.ok(productService.getProductById(id));} @PutMapping("/{id}") public ResponseEntity<ProductDto> update(@PathVariable Long id,@Valid @RequestBody ProductDto dto){return ResponseEntity.ok(productService.updateProduct(id,dto));} @DeleteMapping("/{id}") public ResponseEntity<Void> delete(@PathVariable Long id){productService.deleteProduct(id);return ResponseEntity.noContent().build();} @GetMapping("/search") public ResponseEntity<Page<ProductDto>> search(@RequestParam String name,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ResponseEntity.ok(productService.searchByName(name,page,size));} @GetMapping("/filter/category") public ResponseEntity<Page<ProductDto>> category(@RequestParam Long categoryId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ResponseEntity.ok(productService.filterByCategory(categoryId,page,size));} @GetMapping("/filter/status") public ResponseEntity<Page<ProductDto>> status(@RequestParam String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ResponseEntity.ok(productService.filterByStatus(status,page,size));} @GetMapping("/filter/price") public ResponseEntity<Page<ProductDto>> price(@RequestParam BigDecimal minPrice,@RequestParam BigDecimal maxPrice,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ResponseEntity.ok(productService.filterByPriceRange(minPrice,maxPrice,page,size));} }
