package com.inventory.product.service.impl;
import java.math.BigDecimal;
import org.springframework.beans.BeanUtils;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import com.inventory.product.dto.ProductDto;
import com.inventory.product.entity.*;
import com.inventory.product.exception.ResourceNotFoundException;
import com.inventory.product.repository.*;
import com.inventory.product.service.ProductService;
@Service public class ProductServiceImpl implements ProductService { private final ProductRepository productRepository; private final CategoryRepository categoryRepository; public ProductServiceImpl(ProductRepository productRepository,CategoryRepository categoryRepository){this.productRepository=productRepository;this.categoryRepository=categoryRepository;} public ProductDto saveProduct(ProductDto dto){Product product=new Product();BeanUtils.copyProperties(dto,product);product.setCategory(category(dto.getCategoryId()));return toDto(productRepository.save(product));} public Page<ProductDto> getAllProducts(int page,int size,String sortBy,String sortDir){Sort sort=sortDir.equalsIgnoreCase("desc")?Sort.by(sortBy).descending():Sort.by(sortBy).ascending();return productRepository.findAll(PageRequest.of(page,size,sort)).map(this::toDto);} public ProductDto getProductById(Long id){return toDto(product(id));} public ProductDto updateProduct(Long id,ProductDto dto){Product product=product(id);BeanUtils.copyProperties(dto,product,"id");product.setCategory(category(dto.getCategoryId()));return toDto(productRepository.save(product));} public void deleteProduct(Long id){productRepository.delete(product(id));} public Page<ProductDto> searchByName(String name,int page,int size){return productRepository.findByNameContainingIgnoreCase(name,PageRequest.of(page,size)).map(this::toDto);} public Page<ProductDto> filterByCategory(Long categoryId,int page,int size){return productRepository.findByCategoryId(categoryId,PageRequest.of(page,size)).map(this::toDto);} public Page<ProductDto> filterByStatus(String status,int page,int size){return productRepository.findByStatusIgnoreCase(status,PageRequest.of(page,size)).map(this::toDto);} public Page<ProductDto> filterByPriceRange(BigDecimal minPrice,BigDecimal maxPrice,int page,int size){return productRepository.findByPriceBetween(minPrice,maxPrice,PageRequest.of(page,size)).map(this::toDto);} private Product product(Long id){return productRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Product not found with id: "+id));} private Category category(Long id){return categoryRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Category not found with id: "+id));} private ProductDto toDto(Product product){ProductDto dto=new ProductDto();BeanUtils.copyProperties(product,dto);dto.setCategoryId(product.getCategory().getId());dto.setCategoryName(product.getCategory().getName());return dto;} }
